version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing source NPM dependencies...  
      - cd complexity-analyzer-client
      - npm install
      - cd ..
  build:
    commands:
      - cd complexity-analyzer-client
      - npm run build
      - cd ..
  post_build:
    commands:
      - cd complexity-analyzer-client
      - aws s3 sync build/ s3://complexity-analyzer-app.com
      - cd ..
artifacts:
  files:
    - "**/*"
cache:
  paths:
    - node_modules/**/*
